Move Insert
VRCFury/VRCFury pull request #248
Opened 2024-02-18 07:15 UTC by GameGeek720

Added the ability to set an arbitrary index for Move Menu Item rather than always moving it to the end

2024-03-30 01:13 UTC, AraHaan requested changes

2024-03-30 01:13 UTC, AraHaan commented on com.vrcfury.vrcfury/Editor/VF/Builder/Manager/MenuManager.cs
> +        public bool Move(string from, string to, int index) {
Default this to -1 please.

2024-03-30 01:13 UTC, AraHaan commented on com.vrcfury.vrcfury/Editor/VF/Builder/Manager/MenuManager.cs
> +        public void Insert(VRCExpressionsMenu menu, VRCExpressionsMenu.Control item, int index) {
Same here.

2024-03-30 01:13 UTC, AraHaan commented on com.vrcfury.vrcfury/Editor/VF/Feature/MoveMenuItemBuilder.cs
> +
I feel like it does not need to be listed under "Advanced Options" as it could be seen to be trivial to allow it and not really too Advanced.

2024-06-21 18:00 UTC, SenkyDragon commented
Implemented in c90bb44eb50b1d292fe57991926faf1d3a355b4e

2024-06-21 18:00 UTC, closed without merging